# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Diego
tagline:          'A blog of things'
description:      ''
url:              http://diego2d.com
baseurl:          /

author:
  name:           'Diego Murillo'
  url:            https://diego2d.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ddmurillo/
